const points = {
  // account
  singIn: "/Authenticate/login",
  forgetPassword: "/Authenticate/ForgotPassword",
  rePassword: "/Authenticate/resetPassword",
  // service
  sendPhoto: "/Services/SendPhoto",
  sendEft: "/Services/SendEft",
  getPhoto: "/Services/GetPhoto",
  // Admin-products
  getproducts: "/AdminProduct/GetProducts",
  postProducts: "/AdminProduct/AddUpdateProduct",
  getproduct: "/AdminProduct/GetProduct",
  deleteproducts: "/AdminProduct/DeleteProducts",
  changeStateProduct: "/AdminProduct/PublishProduct",
  // Admin-Users
  setPassword: "/AdminUser/GetUsers",
  getUsers: "/AdminUser/GetUsers",
  getUser: "/AdminUser/GetUser",
  updateUserProfile: "/AdminUser/UpdateUserProfile",
  getUserProfile: "/AdminUser/GetUserProfile",
  postUser: "/AdminUser/AddUser",
  deleteUser: "/AdminUser/DeleteUser",
  changeStateUser: "/AdminUser/ActivateUser",
  getCompanyProfile: "/AdminUser/GetCompanyProfile",
  updateCompanyProfile: "/AdminUser/UpdateCompanyProfile",
  // Admin-categories
  upCategory: "/AdminCategory/CategoryUp",
  getCategorySelect: "/AdminCategory/GetCategoriesAsOptions",
  downCategory: "/AdminCategory/CategoryDown",
  postCategory: "/AdminCategory/AddUpdateCategory",
  getCategories: "/AdminCategory/GetCategories",
  deleteCategory: "/AdminCategory/DeleteCategories",
  // Admin-orders
  getOrders: "/AdminOrder/GetOrders",
  getOrder: "/AdminOrder/GetOrder",
  sendOrder: "/AdminOrder/SendOrder",
  rejectOrder: "/AdminOrder/RejectOrder",
  receiveOrder: "/AdminOrder/ReceiveOrder",
  // Master-Companies
  getCompany: "/MasterAdmin/GetCompany",
  getCompanies: "/MasterAdmin/GetCompanies",
  postCompanies: "/MasterAdmin/AddUpdateCompany",
  deleteCompanies: "/MasterAdmin/DeleteCompanies",
  ChaneActiveCompanies: "/MasterAdmin/ActivateCompany",
  // Master-Users
  master_setPassword: "/MasterUser/SetPassword",
  master_rePassword: "/MasterUser/Repassword",
  master_getUsers: "/MasterUser/GetUsers",
  master_postUser: "/MasterUser/AddMasterUser",
  master_getUser: "/MasterUser/GetMasterUser",
  master_deleteUser: "/MasterUser/DeleteMasterUser",
  master_activateUser: "/MasterUser/ActivateMasterUser"
};

export default points;
